services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      # Works on Linux, macOS, and Windows (using WSL path or native Windows path)
      - ${SEARCH_HOME:-${HOME:-C:/Users/Public/Documents}}:/home/user:ro
    networks:
      - search_network

  backend:
    build: ./backend
    container_name: search_backend
    ports:
      - "3001:3001"
    volumes:
      # Works on Linux, macOS, and Windows
      - ${SEARCH_HOME:-${HOME:-C:/Users/Public/Documents}}:/home/user:ro
      - ${SEARCH_HOME:-${HOME:-C:/Users/Public/Documents}}/.file_open_commands:/app/file_commands
      - search_history_data:/app/data
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - HOST_HOME=${SEARCH_HOME:-${HOME:-C:/Users/Public/Documents}}
      - DB_DIR=/app/data
    depends_on:
      - elasticsearch
    networks:
      - search_network

volumes:
  elasticsearch_data:
    driver: local
  search_history_data:
    driver: local

networks:
  search_network:
    driver: bridge
