services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ${HOME}:/home/user:ro  # Mount current user's home directory as read-only (Linux & macOS)
    networks:
      - search_network

  backend:
    build: ./backend
    container_name: search_backend
    ports:
      - "3001:3001"
    volumes:
      - ${HOME}:/home/user:ro  # Mount current user's home directory as read-only (Linux & macOS)
      - ${HOME}/.file_open_commands:/app/file_commands  # Writable directory for commands
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - HOST_HOME=${HOME}
    depends_on:
      - elasticsearch
    networks:
      - search_network

volumes:
  elasticsearch_data:
    driver: local

networks:
  search_network:
    driver: bridge
